FORMAT: 1A
HOST: http://bustop.apiblueprint.org/

# Bustop

Bustop api allows clients to log into app, list lines, passengers, register lines tracking

# Group Connection

## Authentication for device [/api/auth]

### POST

+ Request (application/json)
    + Attributes
        + imei (number)
        
+ Response 200 (application/json)        

        {
        
            "token": <token>,
        }
+ Response 500 (application/json)

        {
            "error":<message>
        }
        
## Check Authentication of the device [/api]

### GET 
+ Request (application/json)
+ Response 200 (application/json)

        {
            "message": "Bustop",
            "status": "Connected"
        }
        
# Group Lists

## List Passengers [/api/passenger/{line}]
+ Request Headers
        + x-access-token: <token>

+ Parameters
    + line - Id of the line required

### GET

+ Response 200 (application/json)
    + Attributes
        + passengers (array[Passenger])

+ Response 500 (application/json)

        {
            "error":<message>
        }

## List Lines [/api/line]

### GET
+ Request Headers

        + x-access-token: <token>

+ Response 200 (application/json)
    + Attributes
        + lines (array[Line])

+ Response 500 (application/json)

        {
            "error":<message>
        }
## List Vehicles [/api/vehicle]

### GET
+ Request Headers

        + x-access-token: <token>

+ Response 200 (application/json)
    + Attributes
        + vehicles ([Vehicle])

+ Response 500 (application/json)

        {
            "error":<message>
        }
        
## List Drivers [/api/driver]

### GET
+ Request Headers

        + x-access-token: <token>

+ Response 200 (application/json)
    + Attributes
        + drivers ([Driver])

+ Response 500 (application/json)

        {
            "error":<message>
        }
        
#Group Store

## Travel info [/api/travel/store]

### PUT
+ Request Headers

        + x-access-token: <token>
        
+ Request (application/json)
    + Attributes
        + infos (TravelInfo)
        
+ Response 200 (application/json)

        {
            "success":"Salvo"
        }
        
+ Response 500 (application/json)

        {
            "error":<message>
        }

## Passengers [/api/passenger/:id]
    
### POST

+ Request Headers

        + x-access-token: <token>
        
+ Request (application/json)
    + Attributes
        + passengers (array[Passenger])
        
+ Response 200 (application/json)

        {
            "success":"Salvo"
        }
        
+ Response 500 (application/json)

        {
            "error":<message>
        }
        
#Group Check

## Vehicles [/api/vehicle/check]

### POST
+ Request Headers

        + x-access-token: <token>
        
+ Request (application/json)
    + Attributes
        + count (string)
        
+ Response 200 (application/json)        

        {
            "status": Boolean,
        }
+ Response 500 (application/json)

        {
            "error":<message>
        }

##Drivers [/api/driver/check]

### POST

+ Request Headers

        + x-access-token: <token>
        
+ Request (application/json)
    + Attributes
        + count (string)
        
+ Response 200 (application/json)        

        {
            "status": Boolean,
        }
+ Response 500 (application/json)

        {
            "error":<message>
        }
        
##Passengers [/api/passenger/check]

### POST

+ Request Headers

        + x-access-token: <token>

+ Request (application/json)
    + Attributes
        + count (string)
        + line (string)
        
+ Response 200 (application/json)        

        {
            "status": Boolean,
        }
+ Response 500 (application/json)

        {
            "error":<message>
        }
        
##Lines [/api/line/check]

### POST

+ Request Headers

        + x-access-token: <token>

+ Request (application/json)
    + Attributes
        + count (string)
        
+ Response 200 (application/json)        

        {
            "status": Boolean,
        }
+ Response 500 (application/json)

        {
            "error":<message>
        }


# Data Structures

##Device (object)
+ id: String,
+ imei: String,
+ name: String,
+ status: Number

##Driver (object)
+ id: String,
+ name: String,
+ cpf: String,


## Passenger (object)
+ id (string)
+ name (string)
+ cpf (string)
+ avatar (string)

## Line (object)
+ id: String,

+ short_description: String,
+ long_description: String,

+ origin_date_time:Date,
+ destiny_date_time:Date,

+ recurrency:Number,

+ route_destiny: {lat:Number,lng:Number},
+ route_origin: {lat:Number,lng:Number},
+ clients:[{id:String,name:String,brand:String,}],
+ waypoints: [{location:{lat:Number,lng:Number,},stopover:Boolean}],

## Groups
+ id: String,
+ name: String,
+ lines:[String]
+ time_origin: Date,
+ time_destiny:Date

##TravelInfo
+ id_lines:{type:String,required:[true]},
+ cpf:{type:String,required:true,validate: [cpfValidate, "Cpf don't match"],},
+ plate:{type:String,required:[true],validate: [plateValidate, "Plate don't match"],},
+ started_at:{type:Date,required:[true]},
+ passengers:{type:[String]},

##TravelLog
+ id: String,
+ id_travel: String,
+ trigger_at: Date,
+ speed: Number,
+ point: {lat:Number,lng:Number},

###Models DB

##Companies
+ _id: String,
+ fantasy_name: String,
+ social_name: String,
+ phone: Number,
+ cnpj: String,
+ email: String,
##Clients
+ id: String,
+ type: Number,
+ social_name: String,
+ name: String,
+ phone: Number,
+ cnpj: String,
+ cpf: String,
+ email: String,
+ brand: String,
+ companies: [String],

##Lines

+ id: String,
+ short_description: String,
+ long_description: String,
+ route_origin: {lat:Number,lng:Number},

+ route_destiny: {lat:Number,lng:Number},
+ waypoints: [{location:{lat:Number,lng:Number},stopover:true}],
+ origin_date_time: Date,
+ destiny_date_time: Date,
+ companies: [String],
+ clients: [{id:String,name:String,brand:String}],
+ recurrency: Number,
+ daysOfWeek: [Number]

##Vehicles
+ _id: String,
+ status: Number,
+ capacity: Number,
+ plate: String,
+ prefix: String,
+ companies: [String],
+ type: {id:String,name:String},